"""Ingestion against the real database: job claiming, chunk storage, indexes."""

import asyncio
from datetime import timedelta

import asyncpg
import pytest

from app.domain.models import IngestionJob, JobStatus
from app.worker import run_worker
from tests.integration.conftest import Api, PostgresUrls

pytestmark = pytest.mark.integration

GUIDE = b"""# Kubernetes Networking

## Services

A Service gives a set of pods a stable virtual IP address and DNS name.

### ClusterIP

ClusterIP is the default Service type. It is reachable only inside the cluster.

## Ingress

An Ingress routes external HTTP and HTTPS traffic to Services, based on host and path rules.
"""


async def _create_collection(api: Api, name: str = "k8s") -> str:
    response = await api.client.post(
        "/api/v1/collections", json={"name": name}, headers=api.headers
    )
    collection_id: str = response.json()["id"]
    return collection_id


async def _upload(
    api: Api, collection_id: str, content: bytes = GUIDE
) -> dict[str, dict[str, str]]:
    response = await api.client.post(
        f"/api/v1/collections/{collection_id}/documents",
        files={"file": ("networking.md", content, "text/markdown")},
        headers=api.headers,
    )
    assert response.status_code == 202, response.text
    body: dict[str, dict[str, str]] = response.json()
    return body


async def test_upload_then_worker_makes_document_searchable(
    api: Api, migrated_postgres: PostgresUrls
) -> None:
    collection_id = await _create_collection(api)
    uploaded = await _upload(api, collection_id)
    assert uploaded["document"]["status"] == "pending"
    assert uploaded["job"]["status"] == "queued"

    processed = await run_worker(
        api.container, worker_id="test", poll_interval=0.01, stop=asyncio.Event(), once=True
    )
    assert processed == 1

    job = await api.client.get(f"/api/v1/jobs/{uploaded['job']['id']}", headers=api.headers)
    assert job.json()["status"] == "succeeded"
    document = await api.client.get(
        f"/api/v1/documents/{uploaded['document']['id']}", headers=api.headers
    )
    assert document.json()["status"] == "ready"
    assert document.json()["title"] == "Kubernetes Networking"
    assert document.json()["chunk_count"] == 3

    conn = await asyncpg.connect(migrated_postgres.app)
    try:
        rows = await conn.fetch(
            "SELECT heading_path, vector_dims(embedding) AS dims, tsv::text AS tsv "
            "FROM chunks WHERE document_id = $1 ORDER BY ordinal",
            uploaded["document"]["id"],
        )
        assert [r["heading_path"] for r in rows] == [
            ["Services"],
            ["Services", "ClusterIP"],
            ["Ingress"],
        ]
        assert all(r["dims"] == 1024 for r in rows)
        assert "'clusterip'" in rows[1]["tsv"]  # full-text vector generated by Postgres

        # Both retrieval paths work on the stored chunks:
        keyword_hit = await conn.fetchval(
            "SELECT heading_path FROM chunks "
            "WHERE tsv @@ websearch_to_tsquery('english', 'external HTTPS traffic')"
        )
        assert keyword_hit == ["Ingress"]
        query_vector = await api.embedder.embed_query("anything")
        nearest = await conn.fetchval(
            "SELECT count(*) FROM (SELECT id FROM chunks ORDER BY embedding <=> $1::vector "
            "LIMIT 2) AS t",
            str(query_vector),
        )
        assert nearest == 2
    finally:
        await conn.close()


async def test_duplicate_upload_is_409_with_existing_id(api: Api) -> None:
    collection_id = await _create_collection(api)
    first = await _upload(api, collection_id)

    response = await api.client.post(
        f"/api/v1/collections/{collection_id}/documents",
        files={"file": ("copy.md", GUIDE, "text/markdown")},
        headers=api.headers,
    )

    assert response.status_code == 409
    assert first["document"]["id"] in response.json()["detail"]


async def test_reingesting_replaces_chunks(api: Api, migrated_postgres: PostgresUrls) -> None:
    collection_id = await _create_collection(api)
    uploaded = await _upload(api, collection_id)
    stop = asyncio.Event()
    await run_worker(api.container, worker_id="t", poll_interval=0.01, stop=stop, once=True)

    # Re-queue the same document and process again: chunks are swapped, not duplicated.
    async with api.container.unit_of_work() as uow:
        document = await uow.documents.get(uploaded["document"]["id"])  # type: ignore[arg-type]
        assert document is not None
        document.requeue()
        await uow.documents.update(document)
        await uow.ingestion_jobs.add(IngestionJob.for_document(document.id))
        await uow.commit()
    await run_worker(api.container, worker_id="t", poll_interval=0.01, stop=stop, once=True)

    async with api.container.unit_of_work() as uow:
        assert await uow.chunks.count_for_document(document.id) == 3


async def test_concurrent_workers_never_claim_the_same_job(api: Api) -> None:
    collection_id = await _create_collection(api)
    for i in range(3):
        await _upload(api, collection_id, GUIDE + f"\nVariant {i}\n".encode())

    async def claim() -> IngestionJob | None:
        async with api.container.unit_of_work() as uow:
            job = await uow.ingestion_jobs.claim_next("w", timedelta(minutes=15))
            await asyncio.sleep(0.2)  # hold the row lock while the others try
            await uow.commit()
            return job

    claimed = await asyncio.gather(*(claim() for _ in range(4)))

    ids = [job.id for job in claimed if job]
    assert len(ids) == 3
    assert len(set(ids)) == 3  # SKIP LOCKED: each job went to exactly one claimer
    assert all(job.status is JobStatus.RUNNING and job.attempts == 1 for job in claimed if job)
    assert claimed.count(None) == 1


async def test_expired_lease_is_reclaimed(api: Api) -> None:
    collection_id = await _create_collection(api)
    await _upload(api, collection_id)
    async with api.container.unit_of_work() as uow:
        first = await uow.ingestion_jobs.claim_next("crashed-worker", timedelta(minutes=15))
        await uow.commit()
    assert first is not None

    async with api.container.unit_of_work() as uow:
        # Still within the lease: nobody else may take it...
        assert await uow.ingestion_jobs.claim_next("w2", timedelta(minutes=15)) is None
        # ...but once the lease has expired, another worker can.
        again = await uow.ingestion_jobs.claim_next("w2", timedelta(seconds=0))
        await uow.commit()
    assert again is not None and again.id == first.id
    assert again.locked_by == "w2" and again.attempts == 2


async def test_unsupported_upload_is_422(api: Api) -> None:
    collection_id = await _create_collection(api)
    response = await api.client.post(
        f"/api/v1/collections/{collection_id}/documents",
        files={"file": ("slides.pptx", b"PK...", "application/octet-stream")},
        headers=api.headers,
    )
    assert response.status_code == 422
    assert "Unsupported file type" in response.json()["detail"]
