"""The migration applies cleanly and the schema matches the ORM models."""

import asyncpg
import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from tests.integration.conftest import PROJECT_ROOT, PostgresUrls

pytestmark = pytest.mark.integration


def _config(postgres: PostgresUrls) -> Config:
    config = Config(str(PROJECT_ROOT / "alembic.ini"))
    config.attributes["database_url"] = postgres.owner_sqlalchemy
    config.attributes["configure_logging"] = False
    return config


def test_models_and_migrations_are_in_sync(migrated_postgres: PostgresUrls) -> None:
    try:
        command.check(_config(migrated_postgres))
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure message
        pytest.fail(f"ORM models differ from migrations; run `make migration`:\n{exc}")


async def test_app_role_can_use_migrated_tables(migrated_postgres: PostgresUrls) -> None:
    conn = await asyncpg.connect(migrated_postgres.app)
    try:
        tables = await conn.fetch(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_schema = 'rag' AND has_table_privilege(table_schema || '.' || "
            "table_name, 'SELECT, INSERT, UPDATE, DELETE') ORDER BY table_name"
        )
        names = {t["table_name"] for t in tables}
        assert {"collections", "documents", "chunks", "ingestion_jobs", "api_keys"} <= names
    finally:
        await conn.close()


async def test_chunk_indexes_exist(migrated_postgres: PostgresUrls) -> None:
    conn = await asyncpg.connect(migrated_postgres.app)
    try:
        indexes = {
            row["indexname"]: row["indexdef"]
            for row in await conn.fetch(
                "SELECT indexname, indexdef FROM pg_indexes "
                "WHERE schemaname = 'rag' AND tablename = 'chunks'"
            )
        }
        assert "USING hnsw (embedding vector_cosine_ops)" in indexes["ix_chunks_embedding_hnsw"]
        assert "USING gin (tsv)" in indexes["ix_chunks_tsv"]
    finally:
        await conn.close()
